# Supabase Configuration
# Replace the values below with your actual Supabase credentials

[supabase]
url = "https://nezuyvhlcryvefwixypy.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lenV5dmhsY3J5dmVmd2l4eXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNjkzMTcsImV4cCI6MjA3Njk0NTMxN30.TOz4ga9nPbfQW1uZ4VCQtLcHXamts5jkzZkXPM0AjCY"

# How to get your Supabase credentials:
# 1. Go to https://supabase.com/dashboard
# 2. Select your project
# 3. Go to Settings > API
# 4. Copy the "Project URL" and paste it as the 'url' value above
# 5. Copy the "anon public" key and paste it as the 'key' value above
#
# IMPORTANT: Keep this file secure and never commit it to version control!
# Add .streamlit/secrets.toml to your .gitignore file
